### PR TITLE
Impl serializer interface and json serializer

### PR DESCRIPTION
**Pull request by amikai**
This PR is add a feature which describes in #12.
The three thing i do in this PR:
1. Implement the serializer interface.
2. Implement the json format serializer.
3. Write unit test for above.

### CODE REVIEW

**Comment by iankuan** [comment]
It was almost done, isn't it ?  Just give me some unittests.

However, you could read this material, [How to write a good commit message(Chinese)](https://hackmd.io/EwBgRgnAjAZgrAZgLRwBwDYAsTM2AQyVRgHYSkBTfYdKfAEwohnQSA==). I'm not saying you did a bad job. Just have something you can improve.

**Comment by iankuan** [comment]
@as23041248 , please rebase your branch. We import many features like CI and Makefile, which can test your code automatically.

**Review by iankuan — COMMENTED** [review]
Go ahead!

**Review by amikai — COMMENTED** [review]
YOYO
test

**Review by iankuan — APPROVED** [review]
Seems great. By the way, I notice that this branch `feature/serialization` doesn't catch up mainline. Please rebasing it after few minutes.

**Review by iankuan — COMMENTED** [review]
You didn't rebase completely. Did you try `pull XXX --rebase`? The three of last shouldn't appear in your commit msg.

**Review by iankuan — COMMENTED** [review]
No fixup.

**Review by iankuan — CHANGES_REQUESTED** [review]
Meld last two commits into one. Hint: "rebase -i" and then "-f fixup".

**Review by iankuan — APPROVED** [review]

**Pull request merged**
