### PR TITLE
Refactor serializer module and extend it to support file operations

### PR DESCRIPTION
**Pull request by iankuan**
This patch separates into two phases:
1. Refactor current implementation
2. Extend module to support file operations

Refactor (Done)
* Eliminate duplicate semantic between class obj and method
* Avoid confusion of and conflicting with `json` module
* Extract duplicate function to helper functions

Extend (Done)
* Support file operations
* Unittest

### CODE REVIEW

**Comment by amikai** [comment]
95dbbde Is the "improver" a typo in the commit?

**Comment by amikai** [comment]
60b35c5 I think open and close operation in our application is OK, because we use it in general purpose, not in specific area which needs large IO.

**Review by amikai — CHANGES_REQUESTED** [review]
When writing the test case about loads and dumps, we divided it into two separated test method. But test_json_write_read do merges two things. I'd like to say we should use the same way to write these test cases, e.g. If loads and dumps are tested together, write and read should follow this way too.  If load and dumps are tested separated, write and read should be tested separated too.

**Comment by iankuan** [comment]
Without writing into a file first, it can't examine read operation. However, we can just get file context in one file I ask serializer to write. That's same as what I have done too.

**Pull request merged**
